version: "3"
services:

  postgres:
    image: postgres:14-alpine
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=${DB_LOGIN_PROD}
      - POSTGRES_PASSWORD=${DB_PASSWORD_PROD}
      - POSTGRES_DB=${DB_NAME_PROD}
    volumes:
    -  postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    command:
    - redis-server

  bot:
    image: googlesheetbot:1.1.0
    depends_on:
      - postgres
      - redis
    ports:
    - '8333:8333'
  
volumes:
  postgres_data: