"""add vip

Revision ID: 7ac421bac2e2
Revises: 9ccbc0377a6d
Create Date: 2023-06-16 18:14:01.378413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac421bac2e2'
down_revision = '9ccbc0377a6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vip', sa.Boolean(), default=False))
    op.drop_column('users', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'vip')
    # ### end Alembic commands ###
