"""update user model

Revision ID: 947375923b00
Revises: 7ac421bac2e2
Create Date: 2023-06-23 19:16:36.352171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '947375923b00'
down_revision = '7ac421bac2e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
