"""mod users table

Revision ID: 9ccbc0377a6d
Revises: 9864f3b3beb5
Create Date: 2023-06-16 18:10:41.227437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ccbc0377a6d'
down_revision = '9864f3b3beb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.Boolean(), nullable=True))
    op.drop_column('users', 'coints')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('coints', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
